"""Initial complete database schema

Revision ID: ee1ee59a261e
Revises: 
Create Date: 2025-09-16 20:45:50.030008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1ee59a261e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=80), nullable=False),
    sa.Column('away_team', sa.String(length=80), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ml_home', sa.Integer(), nullable=True),
    sa.Column('ml_away', sa.Integer(), nullable=True),
    sa.Column('spread_line', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('spread_home_odds', sa.Integer(), nullable=True),
    sa.Column('spread_away_odds', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game_tag',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'tag_id')
    )
    op.create_table('parlay_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stake', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prop_type', sa.String(length=8), nullable=False),
    sa.Column('line', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('yes_odds', sa.Integer(), nullable=True),
    sa.Column('no_odds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('result_value', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('result_bool', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.Column('bet_type', sa.String(length=10), nullable=False),
    sa.Column('selection', sa.String(length=10), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('line', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stake', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('stake > 0', name='ck_bet_positive_stake'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['prop_id'], ['prop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parlay_leg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parlay_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bet_type', sa.String(length=10), nullable=False),
    sa.Column('selection', sa.String(length=10), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('line', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['parlay_id'], ['parlay_bet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parlay_leg')
    op.drop_table('bet')
    op.drop_table('prop')
    op.drop_table('parlay_bet')
    op.drop_table('game_tag')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('game')
    # ### end Alembic commands ###
