"""Initial migration with prop support

Revision ID: ff1fcce15bf2
Revises: 
Create Date: 2025-09-16 17:47:40.364069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1fcce15bf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game_tag',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'tag_id')
    )
    op.create_table('prop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prop_type', sa.String(length=8), nullable=False),
    sa.Column('line', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('yes_odds', sa.Integer(), nullable=True),
    sa.Column('no_odds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('result_value', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('result_bool', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'prop', ['prop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prop_id')

    op.drop_table('prop')
    op.drop_table('game_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
